# Generated by Django 5.1.6 on 2025-10-01 21:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguredStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yf_ticker', models.CharField(help_text='Yahoo Finance ticker symbol (e.g., AAPL, SAP.DE)', max_length=20, unique=True)),
                ('trading212_ticker', models.CharField(help_text='Trading 212 instrument ticker (e.g., AAPL_EQ, SAPd_EQ)', max_length=20)),
                ('rsi_window', models.IntegerField(default=14, help_text='Window size for RSI calculation.')),
                ('buy_threshold', models.IntegerField(default=35, help_text="RSI level below which a 'Buy' signal is generated.")),
                ('sell_threshold', models.IntegerField(default=65, help_text="RSI level above which a 'Sell' signal is generated.")),
                ('trade_quantity', models.IntegerField(default=1, help_text='Number of shares to buy/sell per trade.')),
                ('is_active_for_trading', models.BooleanField(default=False, help_text='Set to True to enable automated trading for this stock via cron job.')),
                ('last_run', models.DateTimeField(blank=True, help_text='Timestamp of the last time the automated trading logic ran for this stock.', null=True)),
                ('total_realized_pnl', models.DecimalField(decimal_places=2, default=0.0, help_text='Accumulated P&L from closed trades.', max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('signal_generated', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell'), ('Hold', 'Hold')], help_text="Signal that triggered the trade (or 'Hold' if no trade).", max_length=10)),
                ('quantity', models.IntegerField(help_text='Number of shares involved in the trade (absolute value).')),
                ('price_at_execution', models.DecimalField(blank=True, decimal_places=2, help_text='Price at which the order was (or would be) executed.', max_digits=10, null=True)),
                ('order_type', models.CharField(default='Market', help_text='Type of order placed (e.g., Market).', max_length=20)),
                ('trading212_order_id', models.CharField(blank=True, help_text='Order ID returned by Trading 212 API.', max_length=100, null=True)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Simulated', 'Simulated')], default='Simulated', help_text='Status of the trade execution.', max_length=20)),
                ('response_text', models.TextField(blank=True, help_text='Full response from the trading API.', null=True)),
                ('realized_pnl_for_trade', models.DecimalField(blank=True, decimal_places=2, help_text='Realized P&L for this specific trade if it closed a position.', max_digits=15, null=True)),
                ('stock_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading_core.configuredstock')),
            ],
        ),
    ]
