# Generated by Django 5.1.6 on 2025-10-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuredstock',
            name='is_active_for_trading',
            field=models.BooleanField(default=False, help_text='Set to True to enable automated trading for this stock via in-app scheduler.'),
        ),
    ]
