# Generated by Django 5.1.6 on 2025-10-10 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_core', '0002_alter_configuredstock_is_active_for_trading'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open_price', models.FloatField(blank=True, null=True)),
                ('high_price', models.FloatField(blank=True, null=True)),
                ('low_price', models.FloatField(blank=True, null=True)),
                ('close_price', models.FloatField(blank=True, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('rsi', models.FloatField(blank=True, null=True)),
                ('signal', models.CharField(blank=True, choices=[('Buy', 'Buy'), ('Sell', 'Sell'), ('Hold', 'Hold')], max_length=10, null=True)),
                ('stock_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to='trading_core.configuredstock')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('stock_config', 'timestamp')},
            },
        ),
    ]
