# Generated by Django 5.1.6 on 2025-11-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_core', '0003_historicaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trading212Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('workingScheduleId', models.CharField(max_length=50)),
                ('isin', models.CharField(blank=True, max_length=50, null=True)),
                ('currencyCode', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('shortName', models.CharField(max_length=100)),
                ('maxOpenQuantity', models.IntegerField(blank=True, null=True)),
                ('addedOn', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
