# Generated by Django 5.1.6 on 2025-11-16 13:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_core', '0004_trading212instrument'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_ticker', models.CharField(db_index=True, help_text='Trading 212 instrument ticker (e.g., AAPL_US_EQ)', max_length=50)),
                ('instrument_currency', models.CharField(max_length=10)),
                ('instrument_isin', models.CharField(blank=True, max_length=50, null=True)),
                ('instrument_name', models.CharField(max_length=255)),
                ('instrument_short_name', models.CharField(max_length=100)),
                ('average_price_paid', models.DecimalField(decimal_places=5, max_digits=15)),
                ('created_at', models.DateTimeField()),
                ('current_price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('quantity', models.DecimalField(decimal_places=5, max_digits=15)),
                ('quantity_available_for_trading', models.DecimalField(decimal_places=5, max_digits=15)),
                ('quantity_in_pies', models.DecimalField(decimal_places=5, max_digits=15)),
                ('wallet_impact_currency', models.CharField(max_length=10)),
                ('wallet_impact_current_value', models.DecimalField(decimal_places=5, max_digits=15)),
                ('wallet_impact_fx_impact', models.DecimalField(decimal_places=5, max_digits=15)),
                ('wallet_impact_total_cost', models.DecimalField(decimal_places=5, max_digits=15)),
                ('wallet_impact_unrealized_profit_loss', models.DecimalField(decimal_places=5, max_digits=15)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when this data was fetched from the API.')),
            ],
            options={
                'unique_together': {('instrument_ticker',)},
            },
        ),
    ]
