# Generated by Django 5.1.6 on 2025-10-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.FloatField()),
                ('average_price', models.FloatField()),
                ('current_price', models.FloatField()),
                ('value', models.FloatField()),
                ('profit', models.FloatField()),
                ('fx_profit', models.FloatField(default=0)),
                ('year_month', models.CharField(blank=True, max_length=7, null=True)),
                ('currency_code', models.CharField(max_length=10)),
                ('instrument_type', models.CharField(blank=True, max_length=50, null=True)),
                ('average_price_eur', models.FloatField(blank=True, null=True)),
                ('current_price_eur', models.FloatField(blank=True, null=True)),
                ('value_eur', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
