# Generated by Django 5.1.6 on 2025-10-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioholding',
            name='allocated_funds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
