# Generated by Django 5.1.6 on 2025-10-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolioholding_allocated_funds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioholding',
            name='allocated_funds',
            field=models.FloatField(default=0.0),
        ),
    ]
